import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{createClient}from'@supabase/supabase-js';
import{Search,Bell,User,Sparkles,Play,Film,Music2,Gamepad2,Flame,Bot,ChevronRight,Heart,Clock3,Star,X,Send,Home,Compass,ListMusic,Trophy,Settings,Mic,LogIn,LogOut,ExternalLink,Lock,Mail,Eye,EyeOff,Grid2X2,MonitorPlay,Radio,Popcorn}from'lucide-react';
import'./styles.css';

const supabaseUrl=import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey=import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase=supabaseUrl&&supabaseAnonKey?createClient(supabaseUrl,supabaseAnonKey):null;

const apps=[
 {name:'YouTube',type:'Video',icon:Play,url:'https://www.youtube.com',desc:'Videos, creators & live content',tone:'red'},
 {name:'Netflix',type:'Movies',icon:Film,url:'https://www.netflix.com',desc:'Films and series',tone:'red'},
 {name:'Prime Video',type:'Movies',icon:MonitorPlay,url:'https://www.primevideo.com',desc:'Movies and originals',tone:'blue'},
 {name:'Disney+',type:'Movies',icon:Sparkles,url:'https://www.disneyplus.com',desc:'Disney, Marvel and more',tone:'blue'},
 {name:'JioHotstar',type:'Movies',icon:Popcorn,url:'https://www.jiohotstar.com',desc:'Shows, movies and sports',tone:'orange'},
 {name:'Spotify',type:'Music',icon:Music2,url:'https://open.spotify.com',desc:'Music and podcasts',tone:'green'},
 {name:'Apple Music',type:'Music',icon:Radio,url:'https://music.apple.com',desc:'Songs and playlists',tone:'pink'},
 {name:'SoundCloud',type:'Music',icon:Music2,url:'https://soundcloud.com',desc:'Independent music',tone:'orange'},
 {name:'Twitch',type:'Live',icon:MonitorPlay,url:'https://www.twitch.tv',desc:'Live streams and gaming',tone:'purple'},
 {name:'Crunchyroll',type:'Anime',icon:Play,url:'https://www.crunchyroll.com',desc:'Anime streaming',tone:'orange'},
];

const sections=['Home','Watch','Movies','Music','Play','Trending'];

function App(){
 const[active,setActive]=useState('Home');const[search,setSearch]=useState('');const[favorites,setFavorites]=useState([]);
 const[novaOpen,setNovaOpen]=useState(false);const[loginOpen,setLoginOpen]=useState(false);const[user,setUser]=useState(null);const[showPass,setShowPass]=useState(false);const[authMode,setAuthMode]=useState('signin');const[authLoading,setAuthLoading]=useState(false);const[authError,setAuthError]=useState('');const[authSuccess,setAuthSuccess]=useState('');
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setUser(data.session?.user||null));const{data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>setUser(session?.user||null));return()=>subscription.unsubscribe()},[]);
 const[messages,setMessages]=useState([{from:'nova',text:'Hey! I’m NOVA. Tell me what kind of entertainment you feel like right now. ✨'}]);const[draft,setDraft]=useState('');const[thinking,setThinking]=useState(false);
 const filteredApps=useMemo(()=>apps.filter(a=>(active==='Home'||active==='Trending'||a.type===active||active==='Watch'&&['Video','Live'].includes(a.type)||active==='Play'&&a.type==='Live')&&(a.name+a.type+a.desc).toLowerCase().includes(search.toLowerCase())),[active,search]);
 const toggleFavorite=name=>setFavorites(f=>f.includes(name)?f.filter(x=>x!==name):[...f,name]);
 async function askNova(){
  const text=draft.trim();if(!text||thinking)return;setMessages(m=>[...m,{from:'user',text}]);setDraft('');setThinking(true);
  try{
   const endpoint=import.meta.env.VITE_NOVA_API_URL||'/api/nova';
   const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,history:messages.slice(-8)})});
   const data=await r.json().catch(()=>({}));
   if(!r.ok)throw new Error(data.error||'NOVA service is unavailable.');
   setMessages(m=>[...m,{from:'nova',text:data.reply||'I’m here!'}]);
  }catch(err){setMessages(m=>[...m,{from:'nova',text:err.message||'NOVA could not reach its AI service right now. Please try again.'}]);}
  finally{setTimeout(()=>setThinking(false),400);}
 }
 async function handleAuth(e){e.preventDefault();setAuthError('');setAuthSuccess('');if(!supabase){setAuthError('Authentication is not configured yet. Add your Supabase environment variables in Render.');return}const fd=new FormData(e.currentTarget);const email=fd.get('email');const password=fd.get('password');const name=fd.get('name');setAuthLoading(true);try{let result;if(authMode==='signup'){result=await supabase.auth.signUp({email,password,options:{data:{full_name:name},emailRedirectTo:window.location.origin}})}else{result=await supabase.auth.signInWithPassword({email,password})}if(result.error)throw result.error;if(authMode==='signup'){setAuthSuccess('Account created! Check your email if confirmation is enabled.')}else{setLoginOpen(false)}}catch(err){setAuthError(err.message||'Authentication failed.')}finally{setAuthLoading(false)}}
 async function signInWithGoogle(){setAuthError('');if(!supabase){setAuthError('Authentication is not configured yet. Add your Supabase environment variables in Render.');return}const{error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:window.location.origin}});if(error)setAuthError(error.message)}
 async function logout(){if(supabase)await supabase.auth.signOut();else setUser(null)}
 return <div className="app-shell"><div className="ambient ambient-one"/><div className="ambient ambient-two"/>
 <header className="topbar"><button className="brand-wrap brand-button" onClick={()=>setActive('Home')}><div className="brand-mark">N</div><div><div className="brand">NEXURA</div><div className="tagline">Entertainment, reimagined.</div></div></button>
 <nav className="nav">{sections.map(n=><button key={n} className={active===n?'active':''} onClick={()=>setActive(n)}>{n}</button>)}</nav>
 <div className="top-actions"><div className="search-wrap"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search apps & entertainment"/></div><button className="icon-btn"><Bell size={19}/></button>
 {user?<button className="user-chip" onClick={logout} title="Log out"><span>{(user.user_metadata?.full_name||user.email||'U')[0].toUpperCase()}</span><small>{user.user_metadata?.full_name||user.email}</small><LogOut size={15}/></button>:<button className="login-btn" onClick={()=>{setLoginOpen(true);setAuthError('');setAuthSuccess('')}}><LogIn size={17}/> Login</button>}</div></header>
 <main>{active==='Home'&&<section className="hero"><div className="hero-copy"><div className="eyebrow"><Sparkles size={16}/> YOUR ENTERTAINMENT UNIVERSE</div><h1>Everything you watch,<br/><span>listen to and love.</span></h1><p>NEXURA brings your favourite entertainment destinations together in one beautiful hub, with NOVA ready to help you decide what to enjoy next.</p><div className="hero-actions"><button className="primary-btn" onClick={()=>document.getElementById('apps')?.scrollIntoView({behavior:'smooth'})}><Grid2X2 size={18}/> Explore apps</button><button className="secondary-btn" onClick={()=>setNovaOpen(true)}><Bot size={18}/> Ask NOVA</button></div></div>
 <div className="nova-card"><div className="nova-orb"><Sparkles size={30}/></div><div className="nova-label">NOVA AI</div><div className="nova-title">Your entertainment companion.</div><div className="nova-text">Ask for movie ideas, music vibes, anime, videos, or something completely random.</div><button className="mini-arrow" onClick={()=>setNovaOpen(true)}><ChevronRight size={20}/></button></div></section>}
 <section className="section" id="apps"><div className="section-head"><div><div className="section-kicker"><Flame size={15}/> {active==='Home'?'ENTERTAINMENT APPS':active.toUpperCase()}</div><h2>{active==='Home'?'Your entertainment universe':active+' Hub'}</h2></div><div className="stats"><span><Heart size={14}/> {favorites.length} saved</span><span><Grid2X2 size={14}/> {apps.length} destinations</span></div></div>
 <div className="app-grid">{filteredApps.map(a=>{const Icon=a.icon;return <article className={'app-card '+a.tone} key={a.name}><button className={'favorite '+(favorites.includes(a.name)?'saved':'')} onClick={()=>toggleFavorite(a.name)}><Heart size={16} fill={favorites.includes(a.name)?'currentColor':'none'}/></button><div className="app-logo"><Icon size={28}/></div><div className="app-type">{a.type}</div><h3>{a.name}</h3><p>{a.desc}</p><a href={a.url} target="_blank" rel="noreferrer" className="launch-btn">Open officially <ExternalLink size={15}/></a></article>})}</div>{filteredApps.length===0&&<div className="empty-state">No entertainment apps found for “{search}”.</div>}</section>
 <section className="continue-grid"><div className="mini-panel"><Clock3/><div><b>Continue exploring</b><p>Jump back into your favourite entertainment.</p></div><button onClick={()=>setActive('Trending')}>Open <ChevronRight size={15}/></button></div><div className="mini-panel"><Trophy/><div><b>Your NEXURA profile</b><p>{user?'Logged in as '+(user.user_metadata?.full_name||user.email):'Login to personalise your experience.'}</p></div><User size={18}/></div><div className="mini-panel"><ListMusic/><div><b>Your library</b><p>{favorites.length?favorites.join(', '):'Save apps you love to build it.'}</p></div><Heart size={18}/></div></section>
 <section className="nova-banner"><div className="nova-banner-orb"><Bot size={28}/></div><div className="nova-banner-copy"><div className="section-kicker">POWERED BY NOVA</div><h3>“I have nothing to watch.”</h3><p>That is exactly the kind of problem NOVA was built for.</p></div><button className="primary-btn compact" onClick={()=>setNovaOpen(true)}>Ask NOVA <ChevronRight size={17}/></button></section></main>
 <div className="mobile-nav">{[[Home,'Home'],[Play,'Watch'],[Film,'Movies'],[Music2,'Music'],[Bot,'NOVA']].map(([Icon,n])=><button key={n} className={active===n?'active':''} onClick={()=>n==='NOVA'?setNovaOpen(true):setActive(n)}><Icon size={19}/><span>{n}</span></button>)}</div>
 {loginOpen&&<div className="modal-backdrop" onClick={()=>setLoginOpen(false)}><form className="login-modal" onSubmit={handleAuth} onClick={e=>e.stopPropagation()}><button type="button" className="close-modal" onClick={()=>setLoginOpen(false)}><X size={18}/></button><div className="login-icon"><Lock size={25}/></div><div className="nova-label">NEXURA ACCOUNT · SECURE AUTH</div><h2>{authMode==='signin'?'Welcome back':'Create your account'}</h2><p>{authMode==='signin'?'Sign in to access your personalised NEXURA experience.':'Join NEXURA and build your own entertainment universe.'}</p><div className="auth-tabs"><button type="button" className={authMode==='signin'?'selected':''} onClick={()=>{setAuthMode('signin');setAuthError('');setAuthSuccess('')}}>Sign in</button><button type="button" className={authMode==='signup'?'selected':''} onClick={()=>{setAuthMode('signup');setAuthError('');setAuthSuccess('')}}>Create account</button></div>{authMode==='signup'&&<label>Name<input name="name" required placeholder="Your name"/></label>}<label>Email<input name="email" type="email" required placeholder="you@example.com"/></label><label>Password<div className="password-wrap"><input name="password" type={showPass?'text':'password'} required minLength="6" placeholder="At least 6 characters"/><button type="button" onClick={()=>setShowPass(!showPass)}>{showPass?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label>{authError&&<div className="auth-message error">{authError}</div>}{authSuccess&&<div className="auth-message success">{authSuccess}</div>}<button className="primary-btn login-submit" type="submit" disabled={authLoading}>{authLoading?'Please wait...':authMode==='signin'?'Sign in':'Create account'}</button><div className="auth-divider"><span>or</span></div><button type="button" className="google-btn" onClick={signInWithGoogle}>Continue with Google</button><small className="demo-note">Powered by secure Supabase Authentication. Passwords are never stored in NEXURA's frontend.</small></form></div>}
 {novaOpen&&<div className="modal-backdrop" onClick={()=>setNovaOpen(false)}><section className="nova-modal" onClick={e=>e.stopPropagation()}><div className="nova-modal-head"><div><div className="nova-label">NOVA AI · ONLINE</div><h3>Your entertainment companion</h3></div><button className="icon-btn" onClick={()=>setNovaOpen(false)}><X size={19}/></button></div><div className="chat">{messages.map((m,i)=><div key={i} className={'message '+m.from}>{m.from==='nova'&&<Bot size={17}/>}<span>{m.text}</span></div>)}{thinking&&<div className="message nova"><Bot size={17}/><span>NOVA is thinking...</span></div>}</div><div className="quick-prompts"><button onClick={()=>setDraft("I'm bored")}>I'm bored</button><button onClick={()=>setDraft('Recommend a funny movie')}>Make me laugh</button><button onClick={()=>setDraft('I want relaxing music')}>Relax me</button><button onClick={()=>setDraft('Recommend an anime')}>Anime time</button></div><div className="chat-input"><button><Mic size={18}/></button><input value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>e.key==='Enter'&&askNova()} placeholder="Ask NOVA anything..."/><button className="send" onClick={askNova}><Send size={18}/></button></div></section></div>}
 <footer>© 2026 NEXURA · Entertainment without limits · <Settings size={12}/> Settings</footer></div>
}
createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
