import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{createClient}from'@supabase/supabase-js';
import{Search,Bell,User,Sparkles,Play,Film,Music2,Flame,Bot,ChevronRight,Heart,Clock3,Star,X,Send,Home,ListMusic,Trophy,Settings,Mic,LogIn,LogOut,ExternalLink,Lock,Eye,EyeOff,Grid2X2,MonitorPlay,Radio,Popcorn,Bookmark,Volume2,VolumeX,History,UserRound,Loader2}from'lucide-react';
import'./styles.css';

const supabaseUrl=import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey=import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase=supabaseUrl&&supabaseAnonKey?createClient(supabaseUrl,supabaseAnonKey):null;
const apps=[
{name:'YouTube',type:'Video',icon:Play,url:'https://www.youtube.com',desc:'Videos, creators & live content',tone:'red'},
{name:'Netflix',type:'Movies',icon:Film,url:'https://www.netflix.com',desc:'Films and series',tone:'red'},
{name:'Prime Video',type:'Movies',icon:MonitorPlay,url:'https://www.primevideo.com',desc:'Movies and originals',tone:'blue'},
{name:'Disney+',type:'Movies',icon:Sparkles,url:'https://www.disneyplus.com',desc:'Disney, Marvel and more',tone:'blue'},
{name:'JioHotstar',type:'Movies',icon:Popcorn,url:'https://www.jiohotstar.com',desc:'Shows, movies and sports',tone:'orange'},
{name:'Spotify',type:'Music',icon:Music2,url:'https://open.spotify.com',desc:'Music and podcasts',tone:'green'},
{name:'Apple Music',type:'Music',icon:Radio,url:'https://music.apple.com',desc:'Songs and playlists',tone:'pink'},
{name:'SoundCloud',type:'Music',icon:Music2,url:'https://soundcloud.com',desc:'Independent music',tone:'orange'},
{name:'Twitch',type:'Live',icon:MonitorPlay,url:'https://www.twitch.tv',desc:'Live streams and gaming',tone:'purple'},
{name:'Crunchyroll',type:'Anime',icon:Play,url:'https://www.crunchyroll.com',desc:'Anime streaming',tone:'orange'}];
const sections=['Home','Watch','Movies','Music','Play','Trending'];

function App(){
const[active,setActive]=useState('Home'),[search,setSearch]=useState(''),[favorites,setFavorites]=useState([]),[recent,setRecent]=useState([]);
const[novaOpen,setNovaOpen]=useState(false),[profileOpen,setProfileOpen]=useState(false),[loginOpen,setLoginOpen]=useState(false),[user,setUser]=useState(null),[showPass,setShowPass]=useState(false),[authMode,setAuthMode]=useState('signin'),[authLoading,setAuthLoading]=useState(false),[authError,setAuthError]=useState(''),[authSuccess,setAuthSuccess]=useState('');
const[messages,setMessages]=useState([{from:'nova',text:'Hey! I’m NOVA. Tell me what kind of entertainment you feel like right now. ✨'}]),[draft,setDraft]=useState(''),[thinking,setThinking]=useState(false),[listening,setListening]=useState(false),[voiceOn,setVoiceOn]=useState(true);
const[speechSupported]=useState(()=>typeof window!=='undefined'&&('SpeechRecognition'in window||'webkitSpeechRecognition'in window));
const[discover,setDiscover]=useState({trending:[],movies:[],tv:[],loading:true,error:''});\nconst[selectedMedia,setSelectedMedia]=useState(null),[mediaLoading,setMediaLoading]=useState(false),[mediaError,setMediaError]=useState('');

useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setUser(data.session?.user||null));const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user||null));return()=>subscription.unsubscribe()},[]);
useEffect(()=>{try{setFavorites(JSON.parse(localStorage.getItem('nexura-favorites')||'[]'));setRecent(JSON.parse(localStorage.getItem('nexura-recent')||'[]'))}catch{}},[]);
useEffect(()=>{localStorage.setItem('nexura-favorites',JSON.stringify(favorites));if(user&&supabase)syncCollection('favorites',favorites)},[favorites]);
useEffect(()=>{localStorage.setItem('nexura-recent',JSON.stringify(recent));if(user&&supabase)syncCollection('recent',recent)},[recent]);
useEffect(()=>{fetch('/api/discover').then(r=>r.json()).then(d=>setDiscover({...d,loading:false})).catch(()=>setDiscover({trending:[],movies:[],tv:[],loading:false,error:'Discovery is temporarily unavailable.'}))},[]);
useEffect(()=>{if(!user||!supabase)return;(async()=>{const{data}=await supabase.from('nexura_collections').select('kind,items').eq('user_id',user.id);if(data){const f=data.find(x=>x.kind==='favorites')?.items,r=data.find(x=>x.kind==='recent')?.items;if(Array.isArray(f))setFavorites(f);if(Array.isArray(r))setRecent(r)}})()},[user]);

async function syncCollection(kind,items){try{await supabase.from('nexura_collections').upsert({user_id:user.id,kind,items,updated_at:new Date().toISOString()},{onConflict:'user_id,kind'})}catch{}}
const filteredApps=useMemo(()=>apps.filter(a=>(active==='Home'||active==='Trending'||a.type===active||active==='Watch'&&['Video','Live'].includes(a.type)||active==='Play'&&a.type==='Live')&&(a.name+a.type+a.desc).toLowerCase().includes(search.toLowerCase())),[active,search]);
const toggleFavorite=name=>setFavorites(f=>f.includes(name)?f.filter(x=>x!==name):[...f,name]);
const openApp=a=>{setRecent(r=>[a.name,...r.filter(x=>x!==a.name)].slice(0,6));window.open(a.url,'_blank','noopener,noreferrer')};
function speakNova(text){if(!voiceOn||typeof window==='undefined'||!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=.98;u.pitch=1.05;const v=window.speechSynthesis.getVoices();u.voice=v.find(x=>/en-IN/i.test(x.lang))||v.find(x=>/en-US|en-GB/i.test(x.lang))||null;window.speechSynthesis.speak(u)}
async function askNova(){const text=draft.trim();if(!text||thinking)return;setMessages(m=>[...m,{from:'user',text}]);setDraft('');setThinking(true);try{const r=await fetch('/api/nova',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,history:messages.slice(-10),profile:{favorites,recent}})});const d=await r.json();if(!r.ok)throw new Error(d.error||'NOVA service is unavailable.');const reply=d.reply||'I’m here!';setMessages(m=>[...m,{from:'nova',text:reply}]);speakNova(reply)}catch(e){setMessages(m=>[...m,{from:'nova',text:e.message||'NOVA had a temporary problem.'}])}finally{setThinking(false)}}
function startVoice(){if(!speechSupported||thinking)return;const R=window.SpeechRecognition||window.webkitSpeechRecognition,r=new R();r.lang='en-IN';r.interimResults=true;r.continuous=false;setListening(true);r.onresult=e=>{let t='';for(let i=e.resultIndex;i<e.results.length;i++)t+=e.results[i][0].transcript;setDraft(t)};r.onerror=()=>setListening(false);r.onend=()=>setListening(false);r.start()}
async function handleAuth(e){e.preventDefault();setAuthError('');setAuthSuccess('');if(!supabase)return setAuthError('Authentication is not configured yet.');const fd=new FormData(e.currentTarget),email=fd.get('email'),password=fd.get('password'),name=fd.get('name');setAuthLoading(true);try{const result=authMode==='signup'?await supabase.auth.signUp({email,password,options:{data:{full_name:name},emailRedirectTo:window.location.origin}}):await supabase.auth.signInWithPassword({email,password});if(result.error)throw result.error;if(authMode==='signup')setAuthSuccess('Account created! Check your email if confirmation is enabled.');else setLoginOpen(false)}catch(e){setAuthError(e.message||'Authentication failed.')}finally{setAuthLoading(false)}}
async function google(){if(!supabase)return setAuthError('Authentication is not configured yet.');const{error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:window.location.origin}});if(error)setAuthError(error.message)}
async function logout(){if(supabase)await supabase.auth.signOut();setProfileOpen(false)}

async function openMedia(item){setSelectedMedia({...item,details:null});setMediaError('');setMediaLoading(true);try{const r=await fetch('/api/media/'+(item.mediaType==='tv'?'tv':'movie')+'/'+item.id);const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load details.');setSelectedMedia({...item,details:d})}catch(e){setMediaError(e.message||'Could not load details.')}finally{setMediaLoading(false)}}
const ContentRow=({title,items})=><section className="discovery-section"><div className="section-head"><div><div className="section-kicker"><Flame size={15}/> LIVE DISCOVERY</div><h2>{title}</h2></div></div><div className="poster-row">{items.map(x=><article className="poster-card clickable" key={x.id} onClick={()=>openMedia(x)}><img src={x.poster||''} alt="" loading="lazy"/><div className="poster-overlay"><b>{x.title}</b><span><Star size={12} fill="currentColor"/> {x.rating?.toFixed?.(1)||'—'}</span><p>{x.mediaType==='tv'?'TV Series':'Movie'}</p></div></article>)}</div></section>;

return <div className="app-shell"><div className="ambient ambient-one"/><div className="ambient ambient-two"/>
<header className="topbar"><button className="brand-wrap brand-button" onClick={()=>setActive('Home')}><div className="brand-mark">N</div><div><div className="brand">NEXURA</div><div className="tagline">Entertainment, reimagined.</div></div></button><nav className="nav">{sections.map(n=><button key={n} className={active===n?'active':''} onClick={()=>setActive(n)}>{n}</button>)}</nav><div className="top-actions"><div className="search-wrap"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search apps & entertainment"/></div><button className="icon-btn"><Bell size={19}/></button>{user?<div className="account-actions"><button className="user-chip" onClick={()=>setProfileOpen(true)}><span>{(user.user_metadata?.full_name||user.email||'U')[0].toUpperCase()}</span><small>{user.user_metadata?.full_name||user.email}</small></button><button className="logout-btn" onClick={logout}><LogOut size={16}/><span>Logout</span></button></div>:<button className="login-btn" onClick={()=>setLoginOpen(true)}><LogIn size={17}/> Login</button>}</div></header>
<main>{active==='Home'&&<section className="hero"><div className="hero-copy"><div className="eyebrow"><Sparkles size={16}/> YOUR ENTERTAINMENT UNIVERSE</div><h1>Everything you watch,<br/><span>listen to and love.</span></h1><p>NEXURA now learns what you enjoy, helps you discover what's trending, and gives NOVA context about your entertainment universe.</p><div className="hero-actions"><button className="primary-btn" onClick={()=>document.getElementById('discover')?.scrollIntoView({behavior:'smooth'})}><Flame size={18}/> Discover now</button><button className="secondary-btn" onClick={()=>setNovaOpen(true)}><Bot size={18}/> Ask NOVA</button></div></div><div className="nova-card"><div className="nova-orb"><Sparkles size={30}/></div><div className="nova-label">NOVA AI · PERSONALIZED</div><div className="nova-title">Your entertainment companion.</div><div className="nova-text">NOVA can use your saved apps and recent activity to make better recommendations.</div><button className="mini-arrow" onClick={()=>setNovaOpen(true)}><ChevronRight size={20}/></button></div></section>}
<section className="section" id="apps"><div className="section-head"><div><div className="section-kicker"><Grid2X2 size={15}/> {active==='Home'?'ENTERTAINMENT APPS':active.toUpperCase()}</div><h2>{active==='Home'?'Your entertainment universe':active+' Hub'}</h2></div><div className="stats"><span><Heart size={14}/> {favorites.length} saved</span><span><History size={14}/> {recent.length} recent</span></div></div><div className="app-grid">{filteredApps.map(a=>{const Icon=a.icon;return <article className={'app-card '+a.tone} key={a.name}><button className={'favorite '+(favorites.includes(a.name)?'saved':'')} onClick={()=>toggleFavorite(a.name)}><Heart size={16} fill={favorites.includes(a.name)?'currentColor':'none'}/></button><div className="app-logo"><Icon size={28}/></div><div className="app-type">{a.type}</div><h3>{a.name}</h3><p>{a.desc}</p><button className="launch-btn" onClick={()=>openApp(a)}>Open officially <ExternalLink size={15}/></button></article>})}</div></section>
<section className="library-grid"><div className="library-card"><Bookmark/><h3>My Library</h3><p>{favorites.length?favorites.join(' · '):'Save your favourite apps to build your library.'}</p></div><div className="library-card"><History/><h3>Recently Opened</h3><p>{recent.length?recent.join(' · '):'Your recently opened apps will appear here.'}</p></div><div className="library-card"><Bot/><h3>NOVA Knows Your Vibe</h3><p>{favorites.length?'Your saved favourites help NOVA personalise recommendations.':'Save some apps and ask NOVA for personalised recommendations.'}</p></div></section>
<div id="discover">{discover.loading?<div className="discovery-loading"><Loader2 className="spin"/> Loading real entertainment discovery...</div>:discover.trending.length?<><ContentRow title="Trending Now" items={discover.trending}/><ContentRow title="Popular Movies" items={discover.movies}/><ContentRow title="Top TV Shows" items={discover.tv}/></>:<div className="empty-state">{discover.error||'Add TMDB_API_KEY in Render to activate live discovery.'}</div>}</div>
<section className="nova-banner"><div className="nova-banner-orb"><Bot size={28}/></div><div className="nova-banner-copy"><div className="section-kicker">POWERED BY NOVA</div><h3>“I have nothing to watch.”</h3><p>Now NOVA can use your NEXURA preferences to help solve that.</p></div><button className="primary-btn compact" onClick={()=>setNovaOpen(true)}>Ask NOVA <ChevronRight size={17}/></button></section></main>
<div className="mobile-nav">{[[Home,'Home'],[Play,'Watch'],[Film,'Movies'],[Music2,'Music'],[Bot,'NOVA']].map(([I,n])=><button key={n} className={active===n?'active':''} onClick={()=>n==='NOVA'?setNovaOpen(true):setActive(n)}><I size={19}/><span>{n}</span></button>)}</div>
{profileOpen&&<div className="modal-backdrop" onClick={()=>setProfileOpen(false)}><section className="profile-modal" onClick={e=>e.stopPropagation()}><button className="close-modal" onClick={()=>setProfileOpen(false)}><X size={18}/></button><div className="profile-avatar">{(user.user_metadata?.full_name||user.email||'U')[0].toUpperCase()}</div><div className="nova-label">YOUR NEXURA PROFILE</div><h2>{user.user_metadata?.full_name||'NEXURA Member'}</h2><p>{user.email}</p><div className="profile-stats"><span><Heart/> {favorites.length} Saved</span><span><History/> {recent.length} Recent</span></div><h3>Your Library</h3><div className="profile-list">{favorites.length?favorites.map(x=><span key={x}>{x}</span>):'Nothing saved yet.'}</div></section></div>}
{loginOpen&&<div className="modal-backdrop" onClick={()=>setLoginOpen(false)}><form className="login-modal" onSubmit={handleAuth} onClick={e=>e.stopPropagation()}><button type="button" className="close-modal" onClick={()=>setLoginOpen(false)}><X size={18}/></button><div className="login-icon"><Lock size={25}/></div><div className="nova-label">NEXURA ACCOUNT · SECURE AUTH</div><h2>{authMode==='signin'?'Welcome back':'Create your account'}</h2><div className="auth-tabs"><button type="button" className={authMode==='signin'?'selected':''} onClick={()=>setAuthMode('signin')}>Sign in</button><button type="button" className={authMode==='signup'?'selected':''} onClick={()=>setAuthMode('signup')}>Create account</button></div>{authMode==='signup'&&<label>Name<input name="name" required placeholder="Your name"/></label>}<label>Email<input name="email" type="email" required placeholder="you@example.com"/></label><label>Password<div className="password-wrap"><input name="password" type={showPass?'text':'password'} required minLength="6"/><button type="button" onClick={()=>setShowPass(!showPass)}>{showPass?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label>{authError&&<div className="auth-message error">{authError}</div>}{authSuccess&&<div className="auth-message success">{authSuccess}</div>}<button className="primary-btn login-submit" disabled={authLoading}>{authLoading?'Please wait...':authMode==='signin'?'Sign in':'Create account'}</button><div className="auth-divider"><span>or</span></div><button type="button" className="google-btn" onClick={google}>Continue with Google</button></form></div>}
{selectedMedia&&<div className="modal-backdrop media-backdrop" onClick={()=>setSelectedMedia(null)}><section className="media-modal" onClick={e=>e.stopPropagation()}><button className="close-modal" onClick={()=>setSelectedMedia(null)}><X size={18}/></button>{mediaLoading?<div className="media-loading"><Loader2 className="spin"/> Loading movie details...</div>:mediaError?<div className="media-loading">{mediaError}</div>:<><div className="media-hero" style={{backgroundImage:selectedMedia.details?.backdrop?'linear-gradient(90deg,rgba(11,12,25,.98),rgba(11,12,25,.45)),url('+selectedMedia.details.backdrop+')':undefined}}><div><div className="nova-label">{selectedMedia.mediaType==='tv'?'TV SERIES':'MOVIE'} · {selectedMedia.details?.year||''}</div><h2>{selectedMedia.details?.title||selectedMedia.title}</h2><p>{selectedMedia.details?.overview}</p><div className="media-meta"><span><Star size={15} fill="currentColor"/> {selectedMedia.details?.rating?.toFixed?.(1)||'—'}</span>{selectedMedia.details?.runtime&&<span>{selectedMedia.details.runtime} min</span>}</div></div></div>{selectedMedia.details?.trailer&&<div className="trailer-wrap"><iframe src={'https://www.youtube-nocookie.com/embed/'+selectedMedia.details.trailer.key+'?rel=0'} title={selectedMedia.details.trailer.name} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/></div>}<div className="watch-section"><h3>Where to watch</h3>{selectedMedia.details?.providers?.length?<div className="provider-list">{selectedMedia.details.providers.map(p=><div className="provider" key={p.name}>{p.logo&&<img src={p.logo} alt=""/>}<span>{p.name}</span></div>)}</div>:<p className="muted">No streaming providers were returned for the selected region.</p>}{selectedMedia.details?.watchLink&&<a className="primary-btn compact watch-link" href={selectedMedia.details.watchLink} target="_blank" rel="noreferrer">Find official options <ExternalLink size={16}/></a>}</div></>}</section></div>}
{novaOpen&&<div className="modal-backdrop" onClick={()=>setNovaOpen(false)}><section className="nova-modal" onClick={e=>e.stopPropagation()}><div className="nova-modal-head"><div><div className="nova-label">NOVA AI · PERSONALIZED</div><h3>Your entertainment companion</h3></div><div className="nova-controls"><button className="icon-btn" onClick={()=>setVoiceOn(v=>!v)} title="Toggle NOVA voice">{voiceOn?<Volume2 size={18}/>:<VolumeX size={18}/>}</button><button className="icon-btn" onClick={()=>setNovaOpen(false)}><X size={19}/></button></div></div><div className="chat">{messages.map((m,i)=><div key={i} className={'message '+m.from}>{m.from==='nova'&&<Bot size={17}/>}<span>{m.text}</span></div>)}{thinking&&<div className="message nova"><Bot size={17}/><span>NOVA is thinking...</span></div>}</div><div className="quick-prompts"><button onClick={()=>setDraft("I'm bored")}>I'm bored</button><button onClick={()=>setDraft('Recommend a funny movie based on my favourites')}>Make me laugh</button><button onClick={()=>setDraft('What should I watch tonight?')}>Tonight</button><button onClick={()=>setDraft('Recommend an anime')}>Anime time</button></div><div className="chat-input"><button className={listening?'mic-btn listening':'mic-btn'} onClick={startVoice} disabled={!speechSupported||thinking}><Mic size={18}/></button><input value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>e.key==='Enter'&&askNova()} placeholder="Ask NOVA anything..."/><button className="send" onClick={askNova}><Send size={18}/></button></div></section></div>}
<footer>© 2026 NEXURA · Entertainment without limits · <Settings size={12}/> Settings</footer></div>}
createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);